- name: Ensure wireguard installed
  ansible.builtin.apt:
    name: wireguard
    state: present
    update_cache: true

- name: Ensure WireGuard directory exists
  file:
    path: /etc/wireguard
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Deploy WireGuard configuration
  template:
    src: wg0.conf.j2
    dest: "/etc/wireguard/wg0.conf"
    owner: root
    group: root
    mode: 0600

- name: Deploy WireGuard configuration (windows) just for copying
  template:
    src: windows.conf.j2
    dest: "/etc/wireguard/windows.conf"
    owner: root
    group: root
    mode: 0600 

- name: Enable and start WireGuard
  systemd:
    name: "wg-quick@wg0"
    enabled: yes
    state: started
